# Generated by Django 6.0.3 on 2026-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
