# Generated by Django 6.0.3 on 2026-03-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
    ]
