# Generated by Django 6.0.3 on 2026-04-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_student_email_studentleave_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="facultyleave",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="studentleave",
            name="student",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.DeleteModel(
            name="Faculty",
        ),
        migrations.DeleteModel(
            name="FacultyLeave",
        ),
        migrations.DeleteModel(
            name="StudentLeave",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
