# Generated by Django 6.0.3 on 2026-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0008_remove_subject_faculty_remove_facultyleave_faculty_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
